import type { Metadata } from "next";
import { Geist, Geist_Mono, Lobster } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const lobster = Lobster({
  weight: "400",
  variable: "--font-lobster",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Absnt Coffee",
  description: "Generated by create next app",
  manifest: "/manifest.json",
  icons: {
    icon: '/logo.jpg',
    apple: '/logo .jpg',
  },
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: "Absnt Coffee",
  },
};

export const viewport = {
  themeColor: "#000000",
};
import { CartProvider } from "@/context/cart-context";
import FloatingCart from "@/components/ui/floating-cart";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${lobster.variable} antialiased`}
      >
        <CartProvider>
          {children}
          <FloatingCart />
        </CartProvider>
      </body>
    </html>
  );
}
